{% set name = "pure_eval" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f04483b16c9429532d2c0ddc96e2b3bb6b2dc37a2bfb0e986248dbfd0b78873

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=44
    - setuptools_scm >=3.4.3
    - wheel
  run:
    - python >=3.6

test:
  imports:
    - {{ name }}

about:
  home: http://github.com/alexmojaki/pure_eval
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Safely evaluate AST nodes without side effects
  doc_url: http://github.com/alexmojaki/pure_eval
  dev_url: http://github.com/alexmojaki/pure_eval

extra:
  recipe-maintainers:
    - alexmojaki
