{% set name = "pure_eval" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f4e983f40564c576c7c8635ae88db5956bb2229d7e9237d03b3c0b0190eaf42

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=41
    - setuptools_scm >=3.4.3
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - pure_eval
    - pure_eval.core
    - pure_eval.my_getattr_static
    - pure_eval.utils
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/alexmojaki/pure_eval
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Safely evaluate AST nodes without side effects
  doc_url: https://github.com/alexmojaki/pure_eval/blob/master/README.md
  dev_url: https://github.com/alexmojaki/pure_eval

extra:
  recipe-maintainers:
    - alexmojaki